// Generated by @opencode-ai/httpapi-codegen. Do not edit.
import { Effect, Schema } from "effect"
import { Sse } from "effect/unstable/encoding"
import { HttpClientError } from "effect/unstable/http"
import { HttpApiClient } from "effect/unstable/httpapi"
import { SkillMarketScopedSharingApi } from "@opencode-ai/protocol/skill-market-api"
import { ClientError } from "./client-error"

type RawClient = HttpApiClient.ForApi<typeof SkillMarketScopedSharingApi>

const mapClientError = <E>(error: E) =>
  HttpClientError.isHttpClientError(error) || Schema.isSchemaError(error) || Sse.Retry.is(error)
    ? new ClientError({ cause: error })
    : error

type Endpoint0_0Request = Parameters<
  RawClient["skillMarket.catalogPrivate"]["skillMarket.catalog.privateInstallGrant"]
>[0]
type Endpoint0_0Input = { readonly publicationID: Endpoint0_0Request["params"]["publicationID"] }
const Endpoint0_0 = (raw: RawClient["skillMarket.catalogPrivate"]) => (input: Endpoint0_0Input) =>
  raw["skillMarket.catalog.privateInstallGrant"]({ params: { publicationID: input["publicationID"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup0 = (raw: RawClient["skillMarket.catalogPrivate"]) => ({ privateInstallGrant: Endpoint0_0(raw) })

const Endpoint1_0 = (raw: RawClient["skillMarket.groups"]) => () =>
  raw["skillMarket.groups.list"]({}).pipe(Effect.mapError(mapClientError))

type Endpoint1_1Request = Parameters<RawClient["skillMarket.groups"]["skillMarket.groups.create"]>[0]
type Endpoint1_1Input = {
  readonly name: Endpoint1_1Request["payload"]["name"]
  readonly description?: Endpoint1_1Request["payload"]["description"]
}
const Endpoint1_1 = (raw: RawClient["skillMarket.groups"]) => (input: Endpoint1_1Input) =>
  raw["skillMarket.groups.create"]({ payload: { name: input["name"], description: input["description"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint1_2Request = Parameters<RawClient["skillMarket.groups"]["skillMarket.groups.detail"]>[0]
type Endpoint1_2Input = { readonly groupID: Endpoint1_2Request["params"]["groupID"] }
const Endpoint1_2 = (raw: RawClient["skillMarket.groups"]) => (input: Endpoint1_2Input) =>
  raw["skillMarket.groups.detail"]({ params: { groupID: input["groupID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint1_3Request = Parameters<RawClient["skillMarket.groups"]["skillMarket.groups.update"]>[0]
type Endpoint1_3Input = {
  readonly groupID: Endpoint1_3Request["params"]["groupID"]
  readonly expectedVersion: Endpoint1_3Request["payload"]["expectedVersion"]
  readonly name?: Endpoint1_3Request["payload"]["name"]
  readonly description?: Endpoint1_3Request["payload"]["description"]
}
const Endpoint1_3 = (raw: RawClient["skillMarket.groups"]) => (input: Endpoint1_3Input) =>
  raw["skillMarket.groups.update"]({
    params: { groupID: input["groupID"] },
    payload: { expectedVersion: input["expectedVersion"], name: input["name"], description: input["description"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint1_4Request = Parameters<RawClient["skillMarket.groups"]["skillMarket.groups.transfer"]>[0]
type Endpoint1_4Input = {
  readonly groupID: Endpoint1_4Request["params"]["groupID"]
  readonly expectedVersion: Endpoint1_4Request["payload"]["expectedVersion"]
  readonly ownerEmployeeID: Endpoint1_4Request["payload"]["ownerEmployeeID"]
}
const Endpoint1_4 = (raw: RawClient["skillMarket.groups"]) => (input: Endpoint1_4Input) =>
  raw["skillMarket.groups.transfer"]({
    params: { groupID: input["groupID"] },
    payload: { expectedVersion: input["expectedVersion"], ownerEmployeeID: input["ownerEmployeeID"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint1_5Request = Parameters<RawClient["skillMarket.groups"]["skillMarket.groups.setStatus"]>[0]
type Endpoint1_5Input = {
  readonly groupID: Endpoint1_5Request["params"]["groupID"]
  readonly expectedVersion: Endpoint1_5Request["payload"]["expectedVersion"]
  readonly status: Endpoint1_5Request["payload"]["status"]
}
const Endpoint1_5 = (raw: RawClient["skillMarket.groups"]) => (input: Endpoint1_5Input) =>
  raw["skillMarket.groups.setStatus"]({
    params: { groupID: input["groupID"] },
    payload: { expectedVersion: input["expectedVersion"], status: input["status"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint1_6Request = Parameters<RawClient["skillMarket.groups"]["skillMarket.groups.members"]>[0]
type Endpoint1_6Input = { readonly groupID: Endpoint1_6Request["params"]["groupID"] }
const Endpoint1_6 = (raw: RawClient["skillMarket.groups"]) => (input: Endpoint1_6Input) =>
  raw["skillMarket.groups.members"]({ params: { groupID: input["groupID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint1_7Request = Parameters<RawClient["skillMarket.groups"]["skillMarket.groups.addMember"]>[0]
type Endpoint1_7Input = {
  readonly groupID: Endpoint1_7Request["params"]["groupID"]
  readonly expectedVersion: Endpoint1_7Request["payload"]["expectedVersion"]
  readonly employeeID: Endpoint1_7Request["payload"]["employeeID"]
}
const Endpoint1_7 = (raw: RawClient["skillMarket.groups"]) => (input: Endpoint1_7Input) =>
  raw["skillMarket.groups.addMember"]({
    params: { groupID: input["groupID"] },
    payload: { expectedVersion: input["expectedVersion"], employeeID: input["employeeID"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint1_8Request = Parameters<RawClient["skillMarket.groups"]["skillMarket.groups.removeMember"]>[0]
type Endpoint1_8Input = {
  readonly groupID: Endpoint1_8Request["params"]["groupID"]
  readonly employeeID: Endpoint1_8Request["params"]["employeeID"]
  readonly expectedVersion: Endpoint1_8Request["payload"]["expectedVersion"]
}
const Endpoint1_8 = (raw: RawClient["skillMarket.groups"]) => (input: Endpoint1_8Input) =>
  raw["skillMarket.groups.removeMember"]({
    params: { groupID: input["groupID"], employeeID: input["employeeID"] },
    payload: { expectedVersion: input["expectedVersion"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup1 = (raw: RawClient["skillMarket.groups"]) => ({
  list: Endpoint1_0(raw),
  create: Endpoint1_1(raw),
  detail: Endpoint1_2(raw),
  update: Endpoint1_3(raw),
  transfer: Endpoint1_4(raw),
  setStatus: Endpoint1_5(raw),
  members: Endpoint1_6(raw),
  addMember: Endpoint1_7(raw),
  removeMember: Endpoint1_8(raw),
})

type Endpoint2_0Request = Parameters<RawClient["skillMarket.submissionSharing"]["skillMarket.submissions.promote"]>[0]
type Endpoint2_0Input = {
  readonly submissionID: Endpoint2_0Request["params"]["submissionID"]
  readonly expectedVersion: Endpoint2_0Request["payload"]["expectedVersion"]
  readonly target: Endpoint2_0Request["payload"]["target"]
}
const Endpoint2_0 = (raw: RawClient["skillMarket.submissionSharing"]) => (input: Endpoint2_0Input) =>
  raw["skillMarket.submissions.promote"]({
    params: { submissionID: input["submissionID"] },
    payload: { expectedVersion: input["expectedVersion"], target: input["target"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint2_1Request = Parameters<
  RawClient["skillMarket.submissionSharing"]["skillMarket.submissions.audienceChange"]
>[0]
type Endpoint2_1Input = {
  readonly submissionID: Endpoint2_1Request["params"]["submissionID"]
  readonly expectedVersion: Endpoint2_1Request["payload"]["expectedVersion"]
  readonly target: Endpoint2_1Request["payload"]["target"]
}
const Endpoint2_1 = (raw: RawClient["skillMarket.submissionSharing"]) => (input: Endpoint2_1Input) =>
  raw["skillMarket.submissions.audienceChange"]({
    params: { submissionID: input["submissionID"] },
    payload: { expectedVersion: input["expectedVersion"], target: input["target"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup2 = (raw: RawClient["skillMarket.submissionSharing"]) => ({
  promote: Endpoint2_0(raw),
  audienceChange: Endpoint2_1(raw),
})

const adaptClient = (raw: RawClient) => ({
  skillMarketRestricted: adaptGroup0(raw["skillMarket.catalogPrivate"]),
  skillMarketGroups: adaptGroup1(raw["skillMarket.groups"]),
  skillMarketSharing: adaptGroup2(raw["skillMarket.submissionSharing"]),
})

export const make = (options?: { readonly baseUrl?: URL | string }) =>
  HttpApiClient.make(SkillMarketScopedSharingApi, options).pipe(Effect.map(adaptClient))
